"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AdminLayout from "@/components/AdminLayout";
import { API_BASE_URL } from "@/lib/api-config";

type Project={id:string;name:string;description?:string|null;logoUrl?:string|null;category:string;status:string;createdAt:string};type Stats={submittedProjects:number;approvedProjects:number;activeRaffles:number;entries:number;users:number};
async function api<T>(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set("Content-Type","application/json");const token=typeof window!=="undefined"?localStorage.getItem("raven_admin_token"):null;if(token)headers.set("Authorization",`Bearer ${token}`);const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers,credentials:"include",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message??`Request failed (${r.status})`);return d as T;}
export default function AdminPage(){const[stats,setStats]=useState<Stats|null>(null);const[projects,setProjects]=useState<Project[]>([]);const[filter,setFilter]=useState("SUBMITTED");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const[o,p]=await Promise.all([api<{stats:Stats}>("/admin/overview"),api<{projects:Project[]}>(`/admin/projects?status=${filter}`)]);setStats(o.stats);setProjects(p.projects??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load admin panel")}finally{setLoading(false)}};useEffect(()=>{void load()},[filter]);
 const approve=async(id:string)=>{setBusy(id);setError("");try{await api(`/project-approval/${id}/approve`,{method:"POST"});setMessage("Project approved and published.");await load()}catch(e){setError(e instanceof Error?e.message:"Approval failed")}finally{setBusy(null)}};
 const delProject=async(id:string,name:string)=>{if(!confirm(`Delete project “${name}”? Its non-completed raffles will be cancelled.`))return;setBusy(id);setError("");setMessage("");try{await api(`/admin/projects/${id}`,{method:"DELETE"});setMessage(`Project “${name}” deleted.`);await load()}catch(e){setError(e instanceof Error?e.message:"Project deletion failed")}finally{setBusy(null)}};
 return <AdminLayout><div className="mx-auto max-w-7xl"><div className="mb-8"><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">OPERATIONS</span><h1 className="mt-2 text-5xl font-medium">Moderation center.</h1><p className="mt-3 text-sm text-zinc-600">Approve projects and manage platform content.</p></div>{error&&<div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mb-5 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">{message}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{stats&&Object.entries({SUBMITTED:stats.submittedProjects,APPROVED:stats.approvedProjects,"ACTIVE RAFFLES":stats.activeRaffles,ENTRIES:stats.entries,USERS:stats.users}).map(([k,v])=><div key={k} className="rounded-xl border border-white/10 bg-[#0d0c11] p-4"><small className="text-[9px] font-black tracking-[.15em] text-zinc-600">{k}</small><b className="mt-2 block text-2xl">{v}</b></div>)}</div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Link href="/admin/raffles" className="rounded-2xl border border-red-500/20 bg-[#0d0c11] p-6 hover:border-red-400/40"><b>Raffle Management</b><p className="mt-1 text-xs text-zinc-600">View, draw, cancel and delete raffles.</p></Link><Link href="/admin/approvals" className="rounded-2xl border border-emerald-500/20 bg-[#0d0c11] p-6"><b>Project Approval</b><p className="mt-1 text-xs text-zinc-600">Review creator submissions.</p></Link><Link href="/admin/users" className="rounded-2xl border border-white/10 bg-[#0d0c11] p-6"><b>User Management</b><p className="mt-1 text-xs text-zinc-600">Manage users and access.</p></Link></div>
 <div className="mt-8 flex flex-wrap gap-2">{["SUBMITTED","APPROVED","REJECTED","ARCHIVED"].map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-lg px-4 py-2 text-[10px] font-black ${filter===s?"bg-white text-black":"border border-white/10 text-zinc-500"}`}>{s}</button>)}<button onClick={()=>void load()} className="ml-auto rounded-lg border border-white/10 px-4 py-2 text-[10px] font-bold">Refresh</button></div>
 {loading?<div className="py-20 text-center text-sm text-zinc-600">Loading projects…</div>:projects.length===0?<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-16 text-center text-sm text-zinc-600">No {filter.toLowerCase()} projects.</div>:<div className="mt-5 grid gap-4">{projects.map(p=><article key={p.id} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-5"><div className="flex items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-xl bg-black">{p.logoUrl?<img src={p.logoUrl} alt="" className="h-full w-full object-cover"/>:p.name[0]}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><h2 className="font-bold">{p.name}</h2><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[9px] text-violet-300">{p.category}</span><span className="rounded-full bg-white/5 px-2 py-1 text-[9px] text-zinc-500">{p.status}</span></div><p className="mt-2 text-sm text-zinc-500">{p.description||"No description provided."}</p></div></div><div className="mt-5 flex flex-wrap gap-2 border-t border-white/5 pt-4"><Link href={`/projects/${p.id}`} target="_blank" className="rounded-lg border border-white/10 px-4 py-2 text-[10px] font-bold">Preview</Link>{p.status==="SUBMITTED"&&<button disabled={busy===p.id} onClick={()=>void approve(p.id)} className="rounded-lg bg-emerald-500 px-4 py-2 text-[10px] font-black text-black">{busy===p.id?"Working…":"Approve & publish"}</button>}{p.status!=="ARCHIVED"&&<button disabled={busy===p.id} onClick={()=>void delProject(p.id,p.name)} className="ml-auto rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-2 text-[10px] font-black text-red-300">{busy===p.id?"Deleting…":"Delete project"}</button>}</div></article>)}</div>}
 </div></AdminLayout>}
