"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import SiteHeader from "../../../components/SiteHeader";
import { API_BASE_URL } from "@/lib/api-config";

type Raffle={id:string;title:string;status:string;prizeName:string;startsAt:string;endsAt:string;winnerCount:number;_count:{entries:number;winners:number;tasks:number}};
type Project={id:string;name:string;projectType?:string;category:string;status:string;logoUrl?:string|null;bannerUrl?:string|null;chain?:string|null;raffles:Raffle[]};
type Draft={id:string;title:string;prizeName:string;updatedAt:string;winnerCount:number;prizeQuantity:number};
async function api<T>(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set("Content-Type","application/json");const token=typeof window!=="undefined"?localStorage.getItem("raven_token"):null;if(token)headers.set("Authorization",`Bearer ${token}`);const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers,credentials:"include",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message??"Request failed");return d as T;}
const buckets=["DRAFT","SCHEDULED","ACTIVE","CLOSED","COMPLETED"] as const;type Bucket=(typeof buckets)[number];
export default function CreatorStudioPage(){const router=useRouter();const[projects,setProjects]=useState<Project[]>([]);const[drafts,setDrafts]=useState<Record<string,Draft[]>>({});const[selected,setSelected]=useState<string|null>(null);const[bucket,setBucket]=useState<Bucket>("DRAFT");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const d=await api<{projects:Project[]}>("/projects/mine");const list=d.projects??[];setProjects(list);if(!selected&&list[0])setSelected(list[0].id);const ds=await Promise.all(list.map(async p=>{try{return[p.id,(await api<{drafts:Draft[]}>(`/raffle-drafts/${p.id}`)).drafts??[]]as const}catch{return[p.id,[]]as const}}));setDrafts(Object.fromEntries(ds));}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const createRaffle=async()=>{if(!selected)return;setBusy(selected);setError("");try{const d=await api<{draftId:string}>(`/raffle-drafts/${selected}`,{method:"POST",body:JSON.stringify({title:"",description:"",prizeName:"",prizeDescription:"",prizeQuantity:1,winnerCount:1,maxEntriesPerUser:1,fairnessAlgorithmVersion:"",raffleType:"RAFFLE",startsAt:"",endsAt:"",tasks:[]})});router.push(`/dashboard/projects/${selected}/drafts/${d.draftId}`)}catch(e){setError(e instanceof Error?e.message:"Unable to create raffle draft")}finally{setBusy(null)}};
 const deleteRaffle=async(id:string)=>{if(!confirm("Delete this raffle? Completed raffles with winners are retained."))return;setBusy(id);setError("");try{await api(`/raffles/${id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete raffle")}finally{setBusy(null)}};
 const rows=useMemo(()=>bucket==="DRAFT"?projects.flatMap(p=>(drafts[p.id]??[]).map(d=>({kind:"draft" as const,project:p,draft:d}))):projects.flatMap(p=>p.raffles.filter(r=>r.status===bucket).map(r=>({kind:"raffle" as const,project:p,raffle:r}))),[bucket,projects,drafts]);
 const counts=useMemo(()=>{const x:Record<Bucket,number>={DRAFT:0,SCHEDULED:0,ACTIVE:0,CLOSED:0,COMPLETED:0};for(const p of projects){x.DRAFT+=(drafts[p.id]??[]).length;for(const r of p.raffles)if(r.status in x)x[r.status as Bucket]++}return x},[projects,drafts]);
 return <main className="min-h-screen bg-[#06060a] text-zinc-100"><SiteHeader/><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 border-b border-white/10 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard" className="text-xs text-zinc-600">← Dashboard</Link><span className="mt-5 block text-[9px] font-black tracking-[.22em] text-violet-300/70">DASHBOARD</span><h1 className="mt-2 text-4xl font-semibold sm:text-5xl">Create and manage.</h1><p className="mt-3 max-w-3xl text-sm text-zinc-500">Select a project, then create its raffle. You control raffles you created.</p></div><div className="flex gap-2"><Link href="/projects/new" className="rounded-xl border border-white/10 px-5 py-3 text-xs font-black">+ New NFT Project</Link><button onClick={()=>void createRaffle()} disabled={!selected||!!busy} className="rounded-xl bg-violet-500 px-5 py-3 text-xs font-black text-white disabled:opacity-40">+ Create Raffle</button></div></div>{error&&<div className="mt-6 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}
 <section className="mt-7 rounded-3xl border border-white/10 bg-[#0d0c11] p-5 sm:p-7"><div className="flex items-center justify-between"><div><span className="text-[9px] font-black tracking-[.18em] text-violet-300/60">YOUR PROJECTS</span><h2 className="mt-2 text-2xl font-semibold">Choose a project</h2></div><span className="text-[10px] text-zinc-600">{projects.length} PROJECT{projects.length===1?"":"S"}</span></div>{loading?<div className="py-12 text-center text-sm text-zinc-600">Loading…</div>:projects.length===0?<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-12 text-center text-sm text-zinc-500">Create your first NFT project.</div>:<div className="mt-5 grid gap-4 md:grid-cols-2">{projects.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`overflow-hidden rounded-2xl border text-left transition ${selected===p.id?"border-violet-400/60 bg-violet-500/5 ring-1 ring-violet-400/30":"border-white/10 bg-black/10 hover:border-white/20"}`}><div className="relative flex min-h-[130px] items-center justify-center overflow-hidden bg-[#16151d] p-2">{p.bannerUrl?<img src={p.bannerUrl} alt="" className="max-h-[180px] w-full object-contain"/>:<div className="h-[130px] w-full bg-gradient-to-br from-violet-950 to-[#121118]"/>}<span className="absolute left-3 top-3 rounded-full bg-black/70 px-2 py-1 text-[9px] font-black">{p.chain??"TBA"}</span><span className="absolute right-3 top-3 rounded-full bg-emerald-500/20 px-2 py-1 text-[9px] font-black text-emerald-300">{selected===p.id?"SELECTED":"SELECT"}</span></div><div className="flex items-center gap-3 p-4"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl bg-black">{p.logoUrl?<img src={p.logoUrl} alt="" className="h-full w-full object-cover"/>:p.name[0]}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{p.name}</div><div className="mt-1 text-[10px] text-zinc-600">{p.status} · {p.projectType??"NFT"}</div></div><span className="text-violet-300">→</span></div></button>)}</div>}</section>
 <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{buckets.map(b=><button key={b} onClick={()=>setBucket(b)} className={`rounded-2xl border p-4 text-left ${bucket===b?"border-violet-400/40 bg-violet-500/5":"border-white/10 bg-[#0d0c11]"}`}><span className="text-[9px] font-black tracking-[.15em] text-zinc-600">{b}</span><b className="mt-2 block text-3xl">{counts[b]}</b></button>)}</div>
 <section className="mt-7 rounded-3xl border border-white/10 bg-[#0d0c11] p-5 sm:p-7"><div className="flex items-center justify-between"><div><span className="text-[9px] font-black tracking-[.18em] text-violet-300/60">{bucket}</span><h2 className="mt-2 text-2xl font-semibold">{bucket==="DRAFT"?"Saved drafts":`${bucket.toLowerCase()} raffles`}</h2></div></div>{rows.length===0?<div className="mt-6 rounded-2xl border border-dashed border-white/10 p-14 text-center text-sm text-zinc-600">No {bucket.toLowerCase()} items.</div>:<div className="mt-6 space-y-3">{rows.map(row=>row.kind==="draft"?<Link key={row.draft.id} href={`/dashboard/projects/${row.project.id}/drafts/${row.draft.id}`} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-black/10 p-5 hover:border-violet-400/30"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-xl bg-black">{row.project.logoUrl?<img src={row.project.logoUrl} alt="" className="h-full w-full object-cover"/>:row.project.name[0]}</div><div className="min-w-0 flex-1"><div className="text-[9px] font-black text-violet-300">DRAFT · {row.project.name}</div><div className="mt-2 truncate text-sm font-semibold">{row.draft.title||"Untitled Draft"}</div></div><span className="text-xs font-bold text-violet-300">Edit →</span></Link>:<div key={row.raffle.id} className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-black/10 p-5 md:flex-row md:items-center"><Link href={`/dashboard/raffles/${row.raffle.id}`} className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[8px] font-black text-violet-300">{row.raffle.status}</span><span className="text-[9px] text-zinc-600">{row.project.name}</span></div><h3 className="mt-2 truncate text-sm font-semibold">{row.raffle.title}</h3><p className="mt-1 text-xs text-zinc-500">{row.raffle.prizeName} · {row.raffle._count.entries} entries · {row.raffle._count.tasks} tasks</p></Link><div className="flex gap-2"><Link href={`/dashboard/raffles/${row.raffle.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-bold">Manage</Link>{!['COMPLETED','DRAWING'].includes(row.raffle.status)&&<button onClick={()=>void deleteRaffle(row.raffle.id)} disabled={busy===row.raffle.id} className="rounded-lg border border-red-500/20 px-3 py-2 text-[10px] font-bold text-red-300 disabled:opacity-40">Delete</button>}</div></div>)}</div>}</section>
 </div></main>;
}
