"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { API_BASE_URL } from "@/lib/api-config";
type Winner = { id: string; userId: string; walletAddressSnapshot: string; selectionRank: number; status: string; notificationStatus: string; selectedAt: string; notifiedAt?: string | null; user?: { displayName?: string | null; username?: string | null; email?: string | null; emailVerifiedAt?: string | null } };
type Data = { raffle: { id: string; title: string; status: string; winnerCount: number; prizeName: string }; winners: Winner[]; viewer: "CREATOR" | "WINNER" };
type GoogleStatus = { connected: boolean; email?: string | null; name?: string | null };

async function api<T>(path: string, options: RequestInit = {}) { const headers = new Headers(options.headers); headers.set("Content-Type", "application/json"); const token = typeof window !== "undefined" ? localStorage.getItem("raven_token") : null; if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers, credentials: "include" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(data.message ?? `Request failed (${response.status})`), { code: data.code }); return data as T; }
function short(value: string) { return value.length > 22 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value; }

export default function WinnersPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<Data | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [google, setGoogle] = useState<GoogleStatus>({ connected: false });
  useEffect(() => {
    const init = async () => {
      try { setData(await api<Data>(`/raffles/${id}/winners`)); const raffleStatus = await api<GoogleStatus>(`/raffles/${id}/winners/export/google-sheets/status`); setGoogle(raffleStatus); }
      catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load winners"); }
    };
    void init();
    const params = new URLSearchParams(window.location.search);
    const result = params.get("google");
    const error = params.get("error");
    if (result === "connected") setMessage("Google Drive connected. Winner Sheets will now be created in your Drive.");
    if (error) setMessage(error);
    if (result || error) window.history.replaceState({}, "", window.location.pathname);
  }, [id]);
  const action = async (path: string) => { setBusy(true); setMessage(""); try { await api(path, { method: "POST" }); const data = await api<Data>(`/raffles/${id}/winners`); setData(data); } catch (e) { setMessage(e instanceof Error ? e.message : "Action failed"); } finally { setBusy(false); } };
  const connectGoogle = () => { window.location.href = `${API_BASE_URL}/auth/google/connect?returnTo=${encodeURIComponent(`/raffles/${id}/winners`)}`; };
  const disconnectGoogle = async () => { setBusy(true); setMessage(""); try { await api(`/auth/google/disconnect`, { method: "POST" }); setGoogle({ connected: false }); setMessage("Google Drive disconnected."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to disconnect Google Drive"); } finally { setBusy(false); } };
  const exportCsv = async () => { setBusy(true); try { const token = localStorage.getItem("raven_token") ?? ""; const response = await fetch(`${API_BASE_URL}/raffles/${id}/winners/export`, { headers: { Authorization: `Bearer ${token}` }, credentials: "include" }); if (!response.ok) throw new Error("Unable to export whitelist"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `raven-oracle-${id}-winners.csv`; a.click(); URL.revokeObjectURL(url); setMessage("Whitelist CSV downloaded."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to export whitelist"); } finally { setBusy(false); } };
  const exportGoogle = async () => { setBusy(true); setMessage(""); try { const result = await api<{ spreadsheetUrl: string }>(`/raffles/${id}/winners/export/google-sheets`, { method: "POST" }); setMessage("Winner Google Sheet created in your Drive. Opening it now…"); window.open(result.spreadsheetUrl, "_blank", "noopener,noreferrer"); } catch (e) { const error = e as Error & { code?: string }; if (error.code === "GOOGLE_NOT_CONNECTED") setMessage("Connect Google Drive first to export the winners directly to your Drive."); else setMessage(error.message || "Unable to export to Google Sheets"); } finally { setBusy(false); } };

  if (!data) return <main className="min-h-screen bg-[#07070a] p-10 text-zinc-400">{message || "Loading winners…"}</main>;
  const creator = data.viewer === "CREATOR";
  return <main className="min-h-screen bg-[#07070a] text-zinc-100"><div className="mx-auto max-w-6xl px-5 py-10">
    <Link href="/dashboard" className="text-xs text-zinc-500 hover:text-white">← Creator Studio</Link>
    <div className="mt-6 rounded-3xl border border-white/10 bg-[#0d0c11] p-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black tracking-[.2em] text-violet-300/70">NFT WHITELIST WINNERS</p><h1 className="mt-2 text-4xl font-semibold">{data.raffle.title}</h1><p className="mt-2 text-sm text-zinc-500">{data.raffle.prizeName} · {data.raffle.status} · {data.winners.length}/{data.raffle.winnerCount} winners</p></div>{creator && <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={exportCsv} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black">Export whitelist CSV</button>{google.connected ? <><button disabled={busy} onClick={exportGoogle} className="rounded-xl bg-emerald-400 px-4 py-3 text-xs font-black text-black">Export to Google Sheets</button><button disabled={busy} onClick={() => void disconnectGoogle()} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black">Disconnect Google</button></> : <button disabled={busy} onClick={connectGoogle} className="rounded-xl bg-white px-4 py-3 text-xs font-black text-black">Connect Google Drive</button>}{data.raffle.status === "CLOSED" && <button disabled={busy} onClick={() => action(`/raffles/${id}/draw`)} className="rounded-xl bg-violet-400 px-5 py-3 text-xs font-black text-black">Draw winners</button>}</div>}</div>{creator && <div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-zinc-500">{google.connected ? <><span className="rounded-full border border-emerald-500/20 bg-emerald-500/5 px-3 py-1.5 text-emerald-300">Google connected</span><span>{google.email}</span></> : <span>Connect Google Drive to create winner sheets directly in the creator’s Drive.</span>}</div>}</div>
    {message && <div className="mt-5 rounded-xl border border-violet-500/20 bg-violet-500/5 p-4 text-sm text-violet-200">{message}</div>}
    <div className="mt-6 grid gap-3">{data.winners.length === 0 ? <div className="rounded-2xl border border-dashed border-white/10 p-12 text-center text-sm text-zinc-600">No winners selected yet.</div> : data.winners.map((winner) => <article key={winner.id} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-violet-400/10 px-2 py-1 text-[9px] font-black text-violet-300">#{winner.selectionRank}</span><span className="rounded-full border border-emerald-500/20 bg-emerald-500/5 px-2 py-1 text-[9px] font-black text-emerald-300">{winner.status}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-zinc-500">Email: {winner.notificationStatus}</span></div><div className="mt-4"><p className="text-[9px] font-black tracking-[.15em] text-zinc-600">WHITELIST WALLET</p><p className="mt-1 break-all font-mono text-sm text-zinc-200">{winner.walletAddressSnapshot}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[9px] font-black tracking-[.15em] text-zinc-600">WINNER</p><p className="mt-1 text-xs text-zinc-400">{winner.user?.username ? `@${winner.user.username}` : winner.user?.displayName ?? short(winner.userId)}</p></div><div><p className="text-[9px] font-black tracking-[.15em] text-zinc-600">CONTACT EMAIL</p><p className="mt-1 text-xs text-zinc-400">{winner.user?.email ?? "No email added"} {winner.user?.emailVerifiedAt ? <span className="text-emerald-300">· verified</span> : <span className="text-amber-300">· unverified</span>}</p></div></div></div>{creator && <div className="flex shrink-0 flex-wrap gap-2">{winner.notificationStatus === "FAILED" || winner.status === "SELECTED" ? <button disabled={busy} onClick={() => action(`/raffles/${id}/winners/${winner.id}/notify`)} className="rounded-lg bg-white px-4 py-2.5 text-[10px] font-black text-black">{winner.notificationStatus === "FAILED" ? "Retry email" : "Send winner email"}</button> : <button disabled={busy} onClick={() => action(`/raffles/${id}/winners/${winner.id}/resend`)} className="rounded-lg border border-white/10 px-4 py-2.5 text-[10px] font-black">Resend email</button>}<span className="rounded-lg border border-emerald-500/15 bg-emerald-500/5 px-4 py-2.5 text-[10px] font-black text-emerald-300">Whitelist ready</span></div>}</div></article>)}</div>
    <div className="mt-7 rounded-2xl border border-violet-400/15 bg-violet-500/5 p-6"><p className="text-[9px] font-black tracking-[.18em] text-violet-300">HOW NFT WINNERS WORK</p><p className="mt-3 text-sm leading-6 text-zinc-400">A selected winner stays the winner. Raven Oracle sends the verified profile Gmail as a notification, while the wallet address above is the address the project uses for its whitelist. There is no claim deadline, claim button, expiration, or automatic replacement.</p></div>
  </div></main>;
}
