"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import SiteHeader from "../../../components/SiteHeader";
import RaffleCaptchaGate from "../../../components/RaffleCaptchaGate";
import { API_BASE_URL } from "@/lib/api-config";

type User = { displayName?: string | null; username?: string | null };
type Social = { id?: string; provider: "X" | "DISCORD"; providerUsername?: string | null; isActive?: boolean };
type Wallet = { id: string; address: string; chain: "EVM" | "SOLANA"; network: string; status?: string };
type Project = { id?: string; name?: string | null; logoUrl?: string | null; bannerUrl?: string | null; websiteUrl?: string | null; xUrl?: string | null; discordUrl?: string | null };
type Raffle = { id: string; title: string; description?: string | null; prizeName: string; prizeDescription?: string | null; prizeQuantity: number; startsAt: string; endsAt: string; status: string; winnerCount?: number; entryRules?: unknown; project?: Project | null };
type Task = { id: string; type: "DISCORD_JOIN" | "X_FOLLOW" | "X_LIKE" | "X_REPOST"; title: string; description?: string | null; target: string; targetUrl?: string | null; isRequired: boolean };
type TaskResult = { taskId: string; verified: boolean; reason?: string | null };
type Entry = { id: string; status: string; walletAddressSnapshot?: string | null; captchaPassed?: boolean | null; enteredAt: string };

async function api<T>(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers); headers.set("Content-Type", "application/json");
  const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers, credentials: "include", cache: "no-store" });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message ?? `Request failed (${response.status})`);
  return data as T;
}
function urlFor(task: Task, raffle: Raffle | null) {
  const raw = task.targetUrl || (task.type === "X_FOLLOW" ? raffle?.project?.xUrl : task.type === "DISCORD_JOIN" ? raffle?.project?.discordUrl : task.target) || task.target || "";
  if (/^https?:\/\//i.test(raw)) return raw;
  if (task.type === "X_FOLLOW" && /^[A-Za-z0-9_]{1,15}$/.test(raw.replace(/^@/, ""))) return `https://x.com/${raw.replace(/^@/, "")}`;
  return "";
}
function providerFor(task: Task) { return task.type === "DISCORD_JOIN" ? "DISCORD" : "X" as "DISCORD" | "X"; }
function iconFor(task: Task) { return task.type === "DISCORD_JOIN" ? "◉" : task.type === "X_FOLLOW" ? "𝕏" : task.type === "X_LIKE" ? "♡" : "↻"; }
function left(value: string) { const ms = new Date(value).getTime() - Date.now(); if (ms <= 0) return "Ended"; const mins = Math.floor(ms / 60000); const days = Math.floor(mins / 1440); const hours = Math.floor((mins % 1440) / 60); return days ? `${days}d ${hours}h` : `${hours}h ${mins % 60}m`; }
function date(value: string) { return new Date(value).toLocaleDateString([], { day: "numeric", month: "short", year: "numeric" }); }
function rules(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export default function RaffleEntryPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter();
  const [raffle,setRaffle]=useState<Raffle|null>(null),[tasks,setTasks]=useState<Task[]>([]),[results,setResults]=useState<Record<string,TaskResult>>({}),[entry,setEntry]=useState<Entry|null>(null),[user,setUser]=useState<User|null>(null),[socials,setSocials]=useState<Social[]>([]),[wallets,setWallets]=useState<Wallet[]>([]),[walletId,setWalletId]=useState(""),[address,setAddress]=useState(""),[chain,setChain]=useState<"EVM"|"SOLANA">("EVM"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<string|null>(null),[checking,setChecking]=useState<string|null>(null);
  const pendingRef=useRef<string|null>(null);

  const load = useCallback(async()=>{
    try{
      const [r,t]=await Promise.all([api<{raffle:Raffle}>(`/raffles/${id}`),api<{tasks:Task[]}>(`/raffles/${id}/tasks`)]);
      setRaffle(r.raffle); setTasks(t.tasks??[]);
      try{ const e=await api<{entry:Entry}>(`/raffles/${id}/entries/me`); setEntry(e.entry); }catch{ setEntry(null); }
      try{ const me=await api<{user:User}>(`/auth/me`); setUser(me.user); const [s,w]=await Promise.all([api<{accounts:Social[]}>("/social-accounts/"),api<{wallets:Wallet[]}>("/wallets/")]); setSocials(s.accounts??[]); const active=(w.wallets??[]).filter(x=>x.status!=="ARCHIVED"&&x.status!=="DELETED"); setWallets(active); setWalletId(active[0]?.id??""); }catch{setUser(null);setSocials([]);setWallets([]);}
    }catch(e){setMessage(e instanceof Error?e.message:"Unable to load raffle");}finally{setLoading(false);}
  },[id]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const p=sessionStorage.getItem("raven_pending_task"); if(p)setPending(p);},[]);
  useEffect(()=>{pendingRef.current=pending;},[pending]);

  const required=useMemo(()=>tasks.filter(t=>t.isRequired),[tasks]);
  const verified=required.filter(t=>results[t.id]?.verified).length;
  const allVerified=required.length===0||verified===required.length;
  const social=(p:"X"|"DISCORD")=>socials.some(s=>s.provider===p&&s.isActive!==false);
  const active=raffle?.status==="ACTIVE"&&Date.now()>=new Date(raffle.startsAt).getTime()&&Date.now()<=new Date(raffle.endsAt).getTime();
  const walletRequired=rules(raffle?.entryRules).walletRequired!==false;
  const confirmed=entry?.status==="ELIGIBLE"&&!!entry.walletAddressSnapshot;

  const login=()=>router.push(`/login?next=${encodeURIComponent(`/raffles/${id}`)}`);
  const connect=async(provider:"x"|"discord", task?:Task)=>{if(!user)return login(); if(task){sessionStorage.setItem("raven_pending_task",task.id);setPending(task.id);} try{const d=await api<{authorizationUrl:string}>(`/auth/${provider}/start?returnTo=${encodeURIComponent(`/raffle-entry/${id}`)}`);window.location.href=d.authorizationUrl;}catch(e){setMessage(e instanceof Error?e.message:`Unable to connect ${provider}`);}};
  const start=async()=>{if(!user)return login();if(!active){setMessage(raffle?.status==="SCHEDULED"?`Starts in ${left(raffle.startsAt)}`:"Entry is closed");return;}setBusy(true);try{const d=await api<{entry:Entry}>(`/raffles/${id}/entries`,{method:"POST",body:JSON.stringify({})});setEntry(d.entry);setMessage("Entry started. Complete the requirements below.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to enter raffle");}finally{setBusy(false);}};
  const verify=useCallback(async(task:Task,silent=false)=>{if(!user||!entry)return false;setChecking(task.id);try{const d=await api<{verified?:boolean;reason?:string}>(`/raffles/${id}/tasks/${task.id}/verify`,{method:"POST"});const ok=d.verified===true;setResults(c=>({...c,[task.id]:{taskId:task.id,verified:ok,reason:d.reason??null}}));if(!silent)setMessage(ok?`${task.title} verified.`:(d.reason||"Not verified yet."));return ok;}catch(e){if(!silent)setMessage(e instanceof Error?e.message:"Verification failed");return false;}finally{setChecking(null);}},[entry,id,user]);
  const verifyAll=useCallback(async(silent=false)=>{if(!user||!entry)return false;try{const d=await api<{allRequiredTasksVerified:boolean;tasks:TaskResult[];entry:Entry}>(`/raffles/${id}/entries/me/verify-tasks`,{method:"POST"});const next:Record<string,TaskResult>={};for(const x of d.tasks??[])next[x.taskId]=x;setResults(next);setEntry(d.entry);if(!silent)setMessage(d.allRequiredTasksVerified?"All required tasks verified.":"Some required tasks are still incomplete.");return d.allRequiredTasksVerified;}catch(e){if(!silent)setMessage(e instanceof Error?e.message:"Verification failed");return false;}},[entry,id,user]);
  const openTask=async(task:Task)=>{if(!user)return login();if(!entry)return setMessage("Click Enter Raffle first.");const p=providerFor(task);if(!social(p))return connect(p==="X"?"x":"discord",task);const url=urlFor(task,raffle);sessionStorage.setItem("raven_pending_task",task.id);setPending(task.id);if(url){window.open(url,"_blank","noopener,noreferrer");setMessage("Complete the task, return here and verification will run automatically.");}else setMessage("No task URL is configured. Use Verify now after completing it.");};
  const submitWallet=async()=>{if(!user)return login();if(!entry)return setMessage("Enter the raffle first.");if(!allVerified)return setMessage("Complete all required tasks first.");if(!walletId&&!address.trim())return setMessage("Select or paste a payout wallet.");setBusy(true);try{let idToUse=walletId;if(!idToUse){const d=await api<{wallet:Wallet}>("/wallets/",{method:"POST",body:JSON.stringify({address:address.trim(),chain})});idToUse=d.wallet.id;setWallets(w=>[d.wallet,...w]);setWalletId(idToUse);}const d=await api<{entry:Entry}>(`/raffles/${id}/entries/me/wallet`,{method:"PATCH",body:JSON.stringify({walletAddressId:idToUse})});setEntry(d.entry);await verifyAll(false);}catch(e){setMessage(e instanceof Error?e.message:"Unable to submit wallet");}finally{setBusy(false);}};

  useEffect(()=>{if(!entry||!user||!pending)return;const timer=window.setTimeout(async()=>{const task=tasks.find(t=>t.id===pending);if(task){await verify(task,true);await verifyAll(true);}sessionStorage.removeItem("raven_pending_task");setPending(null);},900);return()=>window.clearTimeout(timer);},[entry,pending,tasks,user,verify,verifyAll]);
  useEffect(()=>{const fn=()=>{const p=pendingRef.current;if(!p||!entry)return;const task=tasks.find(t=>t.id===p);if(task){setMessage(`Checking ${task.title}…`);void verify(task,false).then(()=>verifyAll(true));sessionStorage.removeItem("raven_pending_task");setPending(null);}};window.addEventListener("focus",fn);return()=>window.removeEventListener("focus",fn);},[entry,tasks,verify,verifyAll]);

  if(loading)return <main className="min-h-screen bg-[#f5f6f8]"><SiteHeader/><div className="mx-auto max-w-5xl p-16 text-center text-sm text-slate-400">Loading giveaway…</div></main>;
  if(!raffle)return <main className="min-h-screen bg-[#f5f6f8]"><SiteHeader/><div className="mx-auto max-w-5xl p-16 text-center text-sm text-red-500">{message||"Raffle not found"}</div></main>;
  return <main className="min-h-screen bg-[#f5f6f8] text-[#1a1b22] dark:bg-[#07070a] dark:text-zinc-100"><SiteHeader/><RaffleCaptchaGate raffleId={id}><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8"><Link href="/raffles" className="text-xs font-medium text-slate-500 hover:text-slate-900 dark:hover:text-white">Home / All Raffles / {raffle.title}</Link>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
      <div className="rounded-2xl border border-slate-200 bg-white shadow-[0_8px_35px_rgba(15,23,42,.05)] dark:border-white/10 dark:bg-[#0d0c11]">
        <div className="grid md:grid-cols-2"><div className="flex min-h-[320px] flex-col items-center justify-center border-b border-slate-200 p-8 text-center dark:border-white/10 md:border-b-0 md:border-r"><div className="h-20 w-20 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-black">{raffle.project?.logoUrl?<img src={raffle.project.logoUrl} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-2xl font-black">R</div>}</div><h1 className="mt-5 text-3xl font-semibold tracking-tight">{raffle.project?.name||raffle.title}</h1><p className="mt-2 text-sm text-slate-500">{raffle.title}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-400"><span>◉ {required.length} tasks</span><span>•</span><span>🏆 {raffle.winnerCount||1} winners</span></div><div className="mt-5 flex gap-2">{raffle.project?.websiteUrl&&<a href={raffle.project.websiteUrl} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 dark:border-white/10">◎</a>}{raffle.project?.discordUrl&&<a href={raffle.project.discordUrl} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 dark:border-white/10">◉</a>}{raffle.project?.xUrl&&<a href={raffle.project.xUrl} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 dark:border-white/10">𝕏</a>}</div></div><div className="relative min-h-[320px] overflow-hidden bg-slate-200 dark:bg-[#17131f]">{raffle.project?.bannerUrl?<img src={raffle.project.bannerUrl} alt="" className="h-full w-full object-cover"/>:<div className="h-full w-full bg-[radial-gradient(circle_at_70%_30%,rgba(139,92,246,.45),transparent_38%),linear-gradient(135deg,#cbd5e1,#7c3aed)]"/>}<div className="absolute inset-x-5 bottom-5 rounded-xl border border-white/30 bg-black/35 p-4 text-white backdrop-blur-xl"><div className="text-[9px] font-black uppercase tracking-[.18em] text-white/60">Prize</div><div className="mt-1 text-lg font-semibold">{raffle.prizeName}</div><div className="mt-1 text-xs text-white/70">{raffle.prizeQuantity} available</div></div></div></div>
        <div className="grid border-t border-slate-200 sm:grid-cols-3 dark:border-white/10"><div className="border-b border-slate-200 p-5 sm:border-b-0 sm:border-r dark:border-white/10"><div className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">Entries</div><div className="mt-2 text-sm font-semibold">Live raffle</div></div><div className="border-b border-slate-200 p-5 sm:border-b-0 sm:border-r dark:border-white/10"><div className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">End date</div><div className="mt-2 text-sm font-semibold">{date(raffle.endsAt)}</div><div className="mt-1 text-xs text-slate-400">{left(raffle.endsAt)}</div></div><div className="p-5"><div className="text-[9px] font-black uppercase tracking-[.15em] text-slate-400">Winners</div><div className="mt-2 text-sm font-semibold">{raffle.winnerCount||1}</div></div></div>
      </div>

      <aside className="rounded-2xl border border-slate-200 bg-white shadow-[0_8px_35px_rgba(15,23,42,.05)] dark:border-white/10 dark:bg-[#0d0c11]"><div className="border-b border-slate-200 p-5 dark:border-white/10"><div className="text-[9px] font-black uppercase tracking-[.17em] text-slate-400">01 · Entry requirements</div><h2 className="mt-2 text-xl font-semibold">Secure your spot</h2><p className="mt-2 text-xs leading-5 text-slate-500">Open each task, complete it on X or Discord, then come back. Raven Oracle checks your account automatically.</p></div><div className="p-4">{!entry&&<button onClick={start} disabled={busy||!active} className="mb-3 w-full rounded-xl bg-[#3f7cff] px-4 py-3 text-sm font-bold text-white disabled:opacity-40">{active?"Enter Giveaway":raffle.status==="SCHEDULED"?`Starts in ${left(raffle.startsAt)}`:"Entry closed"}</button>}{entry&&<div className="mb-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-700">✓ Entry started</div>}
        {tasks.map(task=>{const r=results[task.id];const p=providerFor(task);const isConnected=social(p);return <div key={task.id} className="border-b border-slate-100 py-4 last:border-b-0 dark:border-white/5"><div className="flex gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${r?.verified?"bg-emerald-100 text-emerald-600":"bg-slate-100 text-slate-600 dark:bg-white/5 dark:text-zinc-300"}`}>{r?.verified?"✓":iconFor(task)}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="text-xs font-semibold">{task.title}</h3>{task.isRequired&&<span className="text-[8px] font-black uppercase tracking-wider text-violet-500">Required</span>}</div><p className="mt-1 text-[10px] leading-4 text-slate-500">{task.description||`Complete the ${p} requirement.`}</p><div className="mt-2 flex gap-2">{entry&&!r?.verified&&<button onClick={()=>void openTask(task)} disabled={checking===task.id||busy} className="rounded-lg bg-slate-900 px-3 py-2 text-[9px] font-bold text-white dark:bg-white dark:text-black">{isConnected?"Open task":"Connect"}</button>}{entry&&!r?.verified&&<button onClick={()=>void verify(task,false)} disabled={checking===task.id||busy} className="rounded-lg border border-slate-200 px-3 py-2 text-[9px] font-bold text-slate-600 dark:border-white/10 dark:text-zinc-300">{checking===task.id?"Checking…":"Verify now"}</button>}</div>{r?.reason&&!r.verified&&<div className="mt-2 rounded-lg bg-amber-50 px-2.5 py-2 text-[9px] leading-4 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300">{r.reason}</div>}</div></div></div>})}
        <div className="mt-3 flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-[10px] dark:bg-white/[.03]"><span className="text-slate-500">{verified}/{required.length} required complete</span><button onClick={()=>void verifyAll(false)} disabled={busy||!entry} className="font-bold text-violet-600 disabled:opacity-40">Verify all</button></div></div>
        {entry&&walletRequired&&<div className="border-t border-slate-200 p-5 dark:border-white/10"><div className="text-[9px] font-black uppercase tracking-[.17em] text-slate-400">02 · Final entry</div><h3 className="mt-2 text-lg font-semibold">Choose your payout wallet</h3><p className="mt-2 text-xs leading-5 text-slate-500">Only available after all required tasks are verified.</p>{wallets.length>0&&<select value={walletId} onChange={e=>setWalletId(e.target.value)} disabled={!allVerified||busy} className="mt-4 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs dark:border-white/10 dark:bg-[#111218]"><option value="">Select connected wallet</option>{wallets.map(w=><option key={w.id} value={w.id}>{w.address.slice(0,6)}…{w.address.slice(-6)} · {w.network}</option>)}</select>}<div className="my-3 text-center text-[8px] uppercase tracking-[.16em] text-slate-400">or paste a wallet</div><div className="grid grid-cols-[92px_1fr] gap-2"><select value={chain} onChange={e=>setChain(e.target.value as "EVM"|"SOLANA")} disabled={!allVerified||busy} className="rounded-xl border border-slate-200 bg-white px-2 py-3 text-xs dark:border-white/10 dark:bg-[#111218]"><option>EVM</option><option>SOLANA</option></select><input value={address} onChange={e=>setAddress(e.target.value)} disabled={!allVerified||busy} placeholder="0x… or Solana" className="min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs dark:border-white/10 dark:bg-[#111218]"/></div><button onClick={submitWallet} disabled={!allVerified||busy||(!walletId&&!address.trim())} className="mt-3 w-full rounded-xl bg-[#3f7cff] px-4 py-3 text-xs font-bold text-white disabled:opacity-40">{busy?"Submitting…":"Enter giveaway"}</button>{confirmed&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-700">✓ Entry confirmed</div>}</div>}
      </aside>
    </div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-[#0d0c11]"><div className="text-[9px] font-black uppercase tracking-[.17em] text-slate-400">Giveaway information</div><h2 className="mt-2 text-xl font-semibold">About this giveaway</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-100 p-4 dark:border-white/5"><span className="text-[9px] text-slate-400">Type</span><p className="mt-1 text-sm font-medium">Raffle</p></div><div className="rounded-xl border border-slate-100 p-4 dark:border-white/5"><span className="text-[9px] text-slate-400">Prize</span><p className="mt-1 text-sm font-medium">{raffle.prizeName}</p></div><div className="rounded-xl border border-slate-100 p-4 dark:border-white/5"><span className="text-[9px] text-slate-400">Start</span><p className="mt-1 text-sm font-medium">{new Date(raffle.startsAt).toLocaleString()}</p></div><div className="rounded-xl border border-slate-100 p-4 dark:border-white/5"><span className="text-[9px] text-slate-400">End</span><p className="mt-1 text-sm font-medium">{new Date(raffle.endsAt).toLocaleString()}</p></div></div>{raffle.description&&<p className="mt-5 border-t border-slate-100 pt-5 text-sm leading-7 text-slate-500 dark:border-white/5">{raffle.description}</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-[#0d0c11]"><div className="text-[9px] font-black uppercase tracking-[.17em] text-slate-400">Prize</div><div className="mt-2 text-2xl font-semibold">{raffle.prizeName}</div><p className="mt-2 text-sm text-slate-500">{raffle.prizeDescription||"Prize awarded to selected raffle winners."}</p><div className="mt-5 rounded-xl bg-slate-50 p-4 dark:bg-white/[.03]"><div className="text-[9px] uppercase tracking-[.15em] text-slate-400">Time remaining</div><div className="mt-1 text-lg font-semibold">{left(raffle.endsAt)}</div></div></section></div>
    </div></RaffleCaptchaGate></main>;
}
