"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import SiteHeader from "../../../components/SiteHeader";
import { API_BASE_URL } from "@/lib/api-config";

type Raffle = { id: string; title: string; status: string; startsAt: string; endsAt: string; captchaRequired: boolean; project?: { id: string; name: string; logoUrl?: string | null } | null };

async function api<T>(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers); headers.set("Content-Type", "application/json");
  const token = typeof window !== "undefined" ? localStorage.getItem("raven_token") : null; if (token) headers.set("Authorization", `Bearer ${token}`);
  const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers, credentials: "include", cache: "no-store" });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message ?? "Request failed"); return data as T;
}

export default function RaffleSecurityPage() {
  const [raffles, setRaffles] = useState<Raffle[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const data = await api<{ raffles: Raffle[] }>("/raffle-security/mine"); setRaffles(data.raffles ?? []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load raffle security settings"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const toggle = async (raffle: Raffle) => { setBusy(raffle.id); setMessage(""); setError(""); try { const data = await api<{ raffle: { captchaRequired: boolean } }>(`/raffle-security/${raffle.id}`, { method: "PATCH", body: JSON.stringify({ captchaRequired: !raffle.captchaRequired }) }); setRaffles((items) => items.map((item) => item.id === raffle.id ? { ...item, captchaRequired: data.raffle.captchaRequired } : item)); setMessage(`${raffle.title}: CAPTCHA ${data.raffle.captchaRequired ? "enabled" : "disabled"}.`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update CAPTCHA setting"); } finally { setBusy(null); } };
  return <main className="min-h-screen bg-[#06060a] text-zinc-100"><SiteHeader /><div className="mx-auto max-w-6xl px-5 py-10"><Link href="/dashboard/creator" className="text-xs text-zinc-600 hover:text-violet-300">← Creator Studio</Link><div className="mt-5"><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">RAFFLE SECURITY</span><h1 className="mt-2 text-4xl font-semibold tracking-tight">Anti-bot protection.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">Turn CAPTCHA protection on for raffles before they are closed or completed. When enabled, participants must pass Cloudflare Turnstile before eligibility can pass.</p></div>{error&&<div className="mt-6 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mt-6 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">{message}</div>}{loading?<div className="py-20 text-center text-sm text-zinc-600">Loading security settings…</div>:raffles.length===0?<div className="mt-8 rounded-2xl border border-dashed border-white/10 p-16 text-center text-sm text-zinc-600">No raffles found. Create a draft or publish a raffle first.</div>:<div className="mt-8 space-y-3">{raffles.map((raffle)=><article key={raffle.id} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-black">{raffle.project?.logoUrl?<img src={raffle.project.logoUrl} alt="" className="h-full w-full rounded-xl object-cover"/>:"R"}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="truncate">{raffle.title || "Untitled Draft"}</b><span className="rounded-full bg-white/5 px-2 py-1 text-[8px] font-black text-zinc-500">{raffle.status}</span></div><p className="mt-1 text-xs text-zinc-600">{raffle.project?.name ?? "Project"} · ends {new Date(raffle.endsAt).toLocaleString()}</p></div><button disabled={busy===raffle.id || ["CLOSED","DRAWING","COMPLETED","CANCELLED"].includes(raffle.status)} onClick={()=>void toggle(raffle)} className={`rounded-xl px-4 py-2.5 text-xs font-black disabled:opacity-40 ${raffle.captchaRequired?"bg-emerald-500 text-black":"border border-white/10 text-zinc-300"}`}>{busy===raffle.id?"Saving…":raffle.captchaRequired?"CAPTCHA Enabled":"Enable CAPTCHA"}</button></div><div className="mt-4 rounded-xl border border-white/5 bg-black/20 p-3 text-xs text-zinc-500">{raffle.captchaRequired?"Participants must complete Turnstile after entering before final eligibility is calculated.":"CAPTCHA is currently optional for this raffle."}</div></article>)}</div>}</div></main>;
}
