"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import ThemeToggle from "../../../components/ThemeToggle";
import { API_BASE_URL } from "@/lib/api-config";
type PendingUser = { id: string; email?: string | null; username?: string | null; createdAt: string; _count: { raffleEntries: number; alphaSubmissions: number; chatMessages: number; walletAddresses: number } };
type Pagination = { page: number; limit: number; total: number; totalPages: number; hasNext: boolean; hasPrevious: boolean };
async function api<T>(path: string, options: RequestInit = {}) { const headers = new Headers(options.headers); headers.set("Content-Type", "application/json"); const token = typeof window !== "undefined" ? localStorage.getItem("raven_admin_token") : null; if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message ?? `Request failed (${response.status})`); return data as T; }
export default function PendingUsersPage() {
  const [users, setUsers] = useState<PendingUser[]>([]); const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 10, total: 0, totalPages: 1, hasNext: false, hasPrevious: false }); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const loadUsers = useCallback(async (page = pagination.page, limit = pagination.limit) => { setLoading(true); setError(""); try { const data = await api<{ success: boolean; users: PendingUser[]; pagination: Pagination }>(`/admin/pending-users?page=${page}&limit=${limit}`); setUsers(data.users); setPagination(data.pagination); setSelectedIds([]); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load pending users"); } finally { setLoading(false); } }, [pagination.page, pagination.limit]);
  useEffect(() => { void loadUsers(1, 10); }, []);
  const selectableUsers = useMemo(() => users.filter((user) => Object.values(user._count).every((count) => count === 0)), [users]); const allSelected = selectableUsers.length > 0 && selectableUsers.every((user) => selectedIds.includes(user.id));
  const toggleUser = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const toggleAll = () => setSelectedIds(allSelected ? [] : selectableUsers.map((user) => user.id));
  const deleteSelected = async () => { if (!selectedIds.length) return; const confirmed = window.confirm(`Permanently delete ${selectedIds.length} selected pending user${selectedIds.length === 1 ? "" : "s"}?\n\nOnly unverified users with no activity can be deleted. This cannot be undone.`); if (!confirmed) return; setBusy(true); setError(""); setMessage(""); try { const data = await api<{ success: boolean; deleted: number; message: string }>("/admin/pending-users/bulk", { method: "DELETE", body: JSON.stringify({ ids: selectedIds }) }); setMessage(data.message); const nextPage = pagination.page > 1 && users.length === selectedIds.length ? pagination.page - 1 : pagination.page; await loadUsers(nextPage, pagination.limit); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete selected users"); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#07070a] text-zinc-100"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#07070a]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[72px] w-[min(1180px,calc(100%-32px))] items-center justify-between px-4"><Link href="/admin" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-violet-500 font-black text-black">R</span><b className="text-sm tracking-[.18em]">RAVEN ORACLE</b></Link><div className="flex items-center gap-3"><ThemeToggle /><Link href="/admin/users" className="rounded-lg border border-white/10 px-3 py-2 text-xs">User Management</Link><Link href="/admin" className="rounded-lg border border-white/10 px-3 py-2 text-xs">Back to Admin</Link></div></div></header><section className="mx-auto w-[min(1180px,calc(100%-32px))] px-4 py-12"><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">ACCOUNT CLEANUP</span><h1 className="mt-2 text-5xl font-medium tracking-tight">Pending users.</h1><p className="mt-3 max-w-2xl text-sm text-zinc-500">Manage unverified pending accounts with pagination and safe bulk cleanup.</p><div className="mt-6 rounded-xl border border-yellow-900/40 bg-yellow-950/20 p-4 text-sm text-yellow-200"><b>Safety rule:</b> only USER accounts that are PENDING, unverified, and have no activity can be deleted.</div>{error && <div className="mt-6 rounded-xl border border-red-900/50 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}{message && <div className="mt-6 rounded-xl border border-emerald-900/50 bg-emerald-950/20 p-4 text-sm text-emerald-300">{message}</div>}
  <div className="mt-8 flex flex-wrap items-center gap-3 rounded-xl border border-white/10 bg-[#0d0c11] p-4"><label className="flex cursor-pointer items-center gap-3 text-xs font-bold"><input type="checkbox" checked={allSelected} onChange={toggleAll} disabled={!selectableUsers.length || loading || busy} className="h-4 w-4 accent-violet-500" /> Select all</label><span className="text-xs text-zinc-500">{selectedIds.length} selected</span><button disabled={!selectedIds.length || busy} onClick={() => void deleteSelected()} className="rounded-lg bg-red-500 px-4 py-2 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{busy ? "Deleting…" : `Delete selected${selectedIds.length ? ` (${selectedIds.length})` : ""}`}</button><div className="ml-auto flex items-center gap-2 text-xs text-zinc-500"><span>Show</span>{[10,20,50].map((limit) => <button key={limit} onClick={() => void loadUsers(1, limit)} className={`rounded-lg px-3 py-2 font-bold ${pagination.limit === limit ? "bg-white text-black" : "border border-white/10"}`}>{limit}</button>)}</div></div>
  {loading ? <div className="py-20 text-center text-sm text-zinc-600">Loading pending users…</div> : users.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-white/10 p-16 text-center text-sm text-zinc-600">No unverified pending users found.</div> : <><div className="mt-5 grid gap-3">{users.map((user) => { const activity = Object.values(user._count).reduce((sum, count) => sum + count, 0); const selectable = activity === 0; return <article key={user.id} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-4"><div className="flex items-start gap-4"><label className="mt-1 shrink-0"><input type="checkbox" checked={selectedIds.includes(user.id)} onChange={() => toggleUser(user.id)} disabled={!selectable || busy} className="h-4 w-4 accent-violet-500" /></label><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{user.email || user.username || "Unknown User"}</b><span className="rounded-full bg-zinc-500/10 px-2 py-1 text-[9px] font-black text-zinc-400">PENDING</span><span className="rounded-full bg-red-500/10 px-2 py-1 text-[9px] font-black text-red-300">NOT VERIFIED</span></div>{user.username && user.email && <p className="mt-1 text-xs text-zinc-500">@{user.username}</p>}<p className="mt-2 text-[10px] text-zinc-600">Created {new Date(user.createdAt).toLocaleString()} • {selectable ? "No activity — selectable" : `${activity} activity record${activity === 1 ? "" : "s"} — protected`}</p></div></div></article>; })}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-zinc-600">Page {pagination.page} of {pagination.totalPages} • {pagination.total} pending users</span><div className="flex gap-2"><button disabled={!pagination.hasPrevious || loading} onClick={() => void loadUsers(pagination.page - 1, pagination.limit)} className="rounded-lg border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Previous</button><button disabled={!pagination.hasNext || loading} onClick={() => void loadUsers(pagination.page + 1, pagination.limit)} className="rounded-lg border border-white/10 px-4 py-2 text-xs disabled:opacity-30">Next</button></div></div></>}</section></main>;
}
