import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireAuth } from "../middleware/auth.js";
const router=Router();const messageSchema=z.object({message:z.string().trim().min(1).max(1000)});
async function getOrCreateGeneral(){return prisma.chatChannel.upsert({where:{slug:"general"},update:{},create:{name:"General",slug:"general",type:"GENERAL"}});}
router.get("/channels",async(_req,res,next)=>{try{const channels=await prisma.chatChannel.findMany({where:{isActive:true},orderBy:[{type:"asc"},{name:"asc"}],select:{id:true,name:true,slug:true,type:true,projectId:true,raffleId:true}});if(channels.length)return res.json({success:true,channels});const general=await getOrCreateGeneral();return res.json({success:true,channels:[general]});}catch(e){next(e);}});
router.get("/channels/:slug/messages",async(req,res,next)=>{try{const channel=await prisma.chatChannel.findUnique({where:{slug:req.params.slug}});if(!channel||!channel.isActive)return res.status(404).json({success:false,message:"Channel not found"});const rawBefore=req.query.before;const before=typeof rawBefore==="string"?new Date(rawBefore):undefined;const messages=await prisma.chatMessage.findMany({where:{channelId:channel.id,moderationStatus:"VISIBLE",deletedAt:null,...(before&&!Number.isNaN(before.getTime())?{createdAt:{lt:before}}:{})},orderBy:{createdAt:"desc"},take:100,include:{user:{select:{username:true,displayName:true,avatarUrl:true}}}});return res.json({success:true,channel,messages:messages.reverse()});}catch(e){next(e);}});
router.post("/channels/:slug/messages",requireAuth,async(req,res,next)=>{try{if(!req.userId)return res.status(401).json({success:false,message:"Authentication required"});const parsed=messageSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,message:"Invalid message"});const channel=await prisma.chatChannel.findUnique({where:{slug:req.params.slug}});if(!channel||!channel.isActive)return res.status(404).json({success:false,message:"Channel not found"});const recent=await prisma.chatMessage.count({where:{channelId:channel.id,userId:req.userId,createdAt:{gt:new Date(Date.now()-10000)},deletedAt:null}});if(recent>=3)return res.status(429).json({success:false,message:"Slow down for a moment"});const message=await prisma.chatMessage.create({data:{channelId:channel.id,userId:req.userId,message:parsed.data.message},include:{user:{select:{username:true,displayName:true,avatarUrl:true}}}});return res.status(201).json({success:true,message});}catch(e){next(e);}});
export default router;
