import { Router, type NextFunction, type Request, type Response } from "express";
import { prisma } from "../lib/prisma.js";
import { requireAuth } from "../middleware/auth.js";
const router = Router();
async function requireAdmin(req: Request, res: Response, next: NextFunction) { if (!req.userId) return res.status(401).json({ success: false, message: "Authentication required" }); const user = await prisma.user.findUnique({ where: { id: req.userId }, select: { role: true, status: true, isAdminApproved: true } }); if (!user || user.status === "BANNED" || user.role !== "ADMIN" || !user.isAdminApproved) return res.status(403).json({ success: false, message: "Admin access required" }); next(); }
router.use((req, res, next) => requireAuth(req, res, next, "admin"), requireAdmin);
const activityRelations = { submittedProjects: true, projectRatings: true, raffleEntries: true, createdRaffles: true, raffleWinners: true, alphaSubmissions: true, pointTransactions: true, createdPointTxns: true, chatMessages: true, raffleTaskVerifications: true, socialAccounts: true, walletAddresses: true } as const;
const pendingWhere = { role: "USER" as const, status: "PENDING" as const, emailVerifiedAt: null, deletedAt: null };
router.get("/", async (req, res, next) => { try { const page = Math.max(1, Number.parseInt(String(req.query.page || "1"), 10) || 1); const requestedLimit = Number.parseInt(String(req.query.limit || "10"), 10) || 10; const limit = [10, 20, 50].includes(requestedLimit) ? requestedLimit : 10; const total = await prisma.user.count({ where: pendingWhere }); const users = await prisma.user.findMany({ where: pendingWhere, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit, select: { id: true, email: true, username: true, createdAt: true, _count: { select: activityRelations } } }); const totalPages = Math.max(1, Math.ceil(total / limit)); res.json({ success: true, users, pagination: { page, limit, total, totalPages, hasNext: page < totalPages, hasPrevious: page > 1 } }); } catch (error) { next(error); } });
async function validatePendingUsers(ids: string[]) { return prisma.user.findMany({ where: { id: { in: ids } }, select: { id: true, email: true, username: true, role: true, status: true, emailVerifiedAt: true, deletedAt: true, _count: { select: activityRelations } } }); }
async function deleteOne(tx: any, user: { id: string; email: string | null }, actorId: string) { await tx.authAuditLog.deleteMany({ where: { userId: user.id } }); await tx.user.delete({ where: { id: user.id } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: "ADMIN_ACTION", entityType: "User", entityId: user.id, summary: `Permanently deleted unverified pending user${user.email ? `: ${user.email}` : ""}`, metadata: { action: "DELETE_UNVERIFIED_PENDING_USER" } } }); }
router.delete("/bulk", async (req, res, next) => { try { const ids = Array.isArray(req.body?.ids) ? [...new Set(req.body.ids.filter((id: unknown): id is string => typeof id === "string"))] : []; if (!ids.length) return res.status(400).json({ success: false, message: "No users selected" }); if (ids.length > 100) return res.status(400).json({ success: false, message: "You can delete up to 100 users at once" }); const users = await validatePendingUsers(ids); const invalid = users.filter((user) => user.role !== "USER" || user.status !== "PENDING" || user.emailVerifiedAt !== null || user.deletedAt !== null || Object.values(user._count).some((count) => count > 0)); if (users.length !== ids.length || invalid.length) return res.status(409).json({ success: false, message: "One or more selected users cannot be deleted because they are verified, active, missing, or have activity.", blockedUserIds: [...new Set([...invalid.map((u) => u.id), ...ids.filter((id) => !users.some((u) => u.id === id))])] }); const actorId = req.userId!; await prisma.$transaction(async (tx) => { for (const user of users) await deleteOne(tx, user, actorId); }); return res.json({ success: true, deleted: users.length, message: `${users.length} pending user${users.length === 1 ? "" : "s"} permanently deleted` }); } catch (error) { next(error); } });
router.delete("/:id", async (req, res, next) => { try { const user = await prisma.user.findUnique({ where: { id: req.params.id }, select: { id: true, email: true, username: true, role: true, status: true, emailVerifiedAt: true, deletedAt: true, _count: { select: activityRelations } } }); if (!user || user.deletedAt) return res.status(404).json({ success: false, message: "User not found" }); if (user.role !== "USER" || user.status !== "PENDING" || user.emailVerifiedAt !== null) return res.status(403).json({ success: false, message: "Only unverified pending user accounts can be permanently deleted here." }); if (Object.values(user._count).some((count) => count > 0)) return res.status(409).json({ success: false, message: "This account has activity and cannot be permanently deleted from this cleanup screen." }); const actorId = req.userId!; await prisma.$transaction(async (tx) => { await deleteOne(tx, user, actorId); }); return res.json({ success: true, message: "Unverified user permanently deleted" }); } catch (error) { next(error); } });
export default router;
