import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireAuth } from "../middleware/auth.js";
import { chainExists, getProjectChains, setProjectChain } from "../services/chain-config.service.js";

const router = Router();
const category = z.enum(["NFT", "TOKEN", "GAME", "TOOL", "DEFI", "COMMUNITY", "OTHER"]);
const imageDataUrl = z.string().regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).max(1_500_000, "Image file is too large. Maximum size is about 1 MB.");
const createSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().trim().max(5000).optional(), websiteUrl: z.string().url().optional().or(z.literal("")), xUrl: z.string().url().optional().or(z.literal("")), discordUrl: z.string().url().optional().or(z.literal("")), logoUrl: imageDataUrl, bannerUrl: imageDataUrl.optional().or(z.literal("")), category: category.default("OTHER"), chain: z.string().trim().min(1).max(80) });
const raffleTaskSchema = z.object({ type: z.enum(["X_FOLLOW", "X_LIKE", "X_REPOST", "DISCORD_JOIN"]), title: z.string().trim().min(1).max(255), description: z.string().trim().max(1000).optional().nullable(), target: z.string().trim().min(1).max(500), targetUrl: z.string().url().optional().nullable().or(z.literal("")), isRequired: z.boolean().default(true) });
const createProjectRaffleSchema = z.object({ title: z.string().trim().min(1).max(200), description: z.string().trim().max(5000).optional(), prizeName: z.string().trim().min(1).max(200), prizeDescription: z.string().trim().max(5000).optional(), prizeQuantity: z.number().int().positive().default(1), startsAt: z.string().datetime(), endsAt: z.string().datetime(), winnerCount: z.number().int().positive().default(1), maxEntriesPerUser: z.number().int().positive().default(1), fairnessAlgorithmVersion: z.string().trim().max(100).default("v1"), tasks: z.array(raffleTaskSchema).min(1) });
function getProjectId(req: Parameters<Parameters<typeof router.get>[1]>[0], res: Parameters<Parameters<typeof router.get>[1]>[1]): string | null { const value = req.params.id; if (typeof value !== "string" || !value) { res.status(400).json({ success: false, message: "Invalid project ID" }); return null; } return value; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 70) || "project"; }
async function uniqueSlug(name: string) { const base = slugify(name); let slug = base; let i = 2; while (await prisma.project.findUnique({ where: { slug } })) slug = `${base}-${i++}`; return slug; }

let projectSchemaReady = false;
let projectSchemaPromise: Promise<void> | null = null;
async function ensureProjectSchema() {
  if (projectSchemaReady) return;
  projectSchemaPromise ??= prisma.$executeRawUnsafe(`ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT`).then(() => { projectSchemaReady = true; }).catch((error) => { projectSchemaPromise = null; throw error; });
  await projectSchemaPromise;
}

router.get("/", async (req, res, next) => { try { await ensureProjectSchema(); const categoryFilter = req.query.category as string | undefined; const status = req.query.status as string | undefined; const search = req.query.search as string | undefined; const limit = Math.min(parseInt(req.query.limit as string) || 100, 100); const where: any = { deletedAt: null }; if (categoryFilter && ["NFT","TOKEN","GAME","TOOL","DEFI","COMMUNITY","OTHER"].includes(categoryFilter)) where.category = categoryFilter; if (status === "APPROVED" || !status) where.status = "APPROVED"; if (search?.trim()) where.OR = [{ name: { contains: search.trim(), mode: "insensitive" } }, { description: { contains: search.trim(), mode: "insensitive" } }]; const projects = await prisma.project.findMany({ where, orderBy: { createdAt: "desc" }, take: limit, select: { id: true, name: true, slug: true, description: true, websiteUrl: true, xUrl: true, discordUrl: true, logoUrl: true, bannerUrl: true, category: true, status: true, createdAt: true } }); const chains = await getProjectChains(projects.map(p => p.id)); const chainByProject = new Map(chains.map(c => [c.projectId, c.chainName])); return res.json({ success: true, projects: projects.map(p => ({ ...p, chain: chainByProject.get(p.id) ?? null })), total: projects.length }); } catch (error) { next(error); } });
router.get("/public", async (req, res, next) => { try { await ensureProjectSchema(); const categoryFilter = req.query.category as string | undefined; const search = req.query.search as string | undefined; const limit = Math.min(parseInt(req.query.limit as string) || 100, 100); const where: any = { deletedAt: null, status: "APPROVED" }; if (categoryFilter && ["NFT","TOKEN","GAME","TOOL","DEFI","COMMUNITY","OTHER"].includes(categoryFilter)) where.category = categoryFilter; if (search?.trim()) where.OR = [{ name: { contains: search.trim(), mode: "insensitive" } }, { description: { contains: search.trim(), mode: "insensitive" } }]; const projects = await prisma.project.findMany({ where, orderBy: { createdAt: "desc" }, take: limit, select: { id: true, name: true, slug: true, description: true, websiteUrl: true, xUrl: true, discordUrl: true, logoUrl: true, bannerUrl: true, category: true, status: true, createdAt: true } }); const chains = await getProjectChains(projects.map(p => p.id)); const chainByProject = new Map(chains.map(c => [c.projectId, c.chainName])); return res.json({ success: true, projects: projects.map(p => ({ ...p, chain: chainByProject.get(p.id) ?? null })), total: projects.length }); } catch (error) { next(error); } });
router.get("/mine", requireAuth, async (req, res, next) => { try { await ensureProjectSchema(); if (!req.userId) return res.status(401).json({ success: false, message: "Authentication required" }); const projects = await prisma.project.findMany({ where: { submittedByUserId: req.userId, deletedAt: null }, orderBy: { createdAt: "desc" }, include: { _count: { select: { raffles: true } }, raffles: { where: { cancelledAt: null }, orderBy: { startsAt: "desc" }, take: 20, select: { id: true, title: true, status: true, prizeName: true, startsAt: true, endsAt: true, winnerCount: true, _count: { select: { entries: true, winners: true } } } } } }); const chains = await getProjectChains(projects.map(p => p.id)); const chainByProject = new Map(chains.map(c => [c.projectId, c.chainName])); return res.json({ success: true, projects: projects.map(p => ({ ...p, chain: chainByProject.get(p.id) ?? null })) }); } catch (error) { next(error); } });
export default router;
