import { Router, type Request, type Response, type NextFunction } from "express";
import { prisma } from "../lib/prisma.js";
import { requireAuth } from "../middleware/auth.js";
import { drawRaffle } from "../services/raffle-draw.service.js";
import { notifyWinner } from "../services/raffle-winner.service.js";

const router = Router();
function getRaffleId(req: Request, res: Response): string | null { const id = req.params.id; if (typeof id !== "string") { res.status(400).json({ success: false, message: "Invalid raffle ID" }); return null; } return id; }
function asyncRoute(handler: (req: Request, res: Response, next: NextFunction) => Promise<void>) { return (req: Request, res: Response, next: NextFunction) => { void handler(req, res, next).catch(next); }; }

router.post("/", asyncRoute(async (_req, res) => { res.status(410).json({ success: false, message: "Raffles are created from the owning project dashboard." }); }));
router.get("/", asyncRoute(async (req, res) => { const status = typeof req.query.status === "string" ? req.query.status : undefined; const raffles = await prisma.raffle.findMany({ where: status ? { status: status as never } : { cancelledAt: null }, orderBy: { startsAt: "desc" }, take: 100, include: { project: { select: { id: true, name: true, logoUrl: true, category: true } } } }); res.json({ success: true, raffles }); }));
router.get("/mine", requireAuth, asyncRoute(async (req, res) => { if (!req.userId) { res.status(401).json({ success: false, message: "Authentication required" }); return; } const entries = await prisma.raffleEntry.findMany({ where: { userId: req.userId }, orderBy: { enteredAt: "desc" }, take: 100, include: { raffle: { include: { project: { select: { id: true, name: true, logoUrl: true, category: true } } } } } }); res.json({ success: true, entries }); }));
router.get("/:id", asyncRoute(async (req, res) => { const raffleId = getRaffleId(req, res); if (!raffleId) return; const raffle = await prisma.raffle.findUnique({ where: { id: raffleId }, include: { project: true } }); if (!raffle) { res.status(404).json({ success: false, message: "Raffle not found" }); return; } const now = new Date(); if (raffle.status === "SCHEDULED" && now >= raffle.startsAt && now < raffle.endsAt) { await prisma.raffle.update({ where: { id: raffle.id }, data: { status: "ACTIVE" } }); raffle.status = "ACTIVE"; } else if ((raffle.status === "ACTIVE" || raffle.status === "SCHEDULED") && now >= raffle.endsAt) { await prisma.raffle.update({ where: { id: raffle.id }, data: { status: "CLOSED" } }); raffle.status = "CLOSED"; } res.json({ success: true, raffle }); }));
router.post("/:id/cancel", requireAuth, asyncRoute(async (req, res) => { if (!req.userId) { res.status(401).json({ success: false, message: "Authentication required" }); return; } const raffleId = getRaffleId(req, res); if (!raffleId) return; const raffle = await prisma.raffle.findUnique({ where: { id: raffleId } }); if (!raffle) { res.status(404).json({ success: false, message: "Raffle not found" }); return; } if (raffle.createdByUserId !== req.userId) { res.status(403).json({ success: false, message: "Only the raffle creator can cancel this raffle" }); return; } if (raffle.cancelledAt) { res.status(400).json({ success: false, message: "Raffle is already cancelled" }); return; } const cancelled = await prisma.raffle.update({ where: { id: raffle.id }, data: { cancelledAt: new Date(), status: "CANCELLED" } }); res.json({ success: true, raffle: cancelled }); }));
router.patch("/:id", requireAuth, async (req, res, next) => { try { const raffleId = req.params.id; if (!raffleId || Array.isArray(raffleId)) return res.status(400).json({ success: false, message: "Invalid raffle ID" }); if (!req.userId) return res.status(401).json({ success: false, message: "Authentication required" }); const parsed = req.body?.status; const allowed = ["DRAFT", "SCHEDULED", "ACTIVE", "CLOSED", "DRAWING", "COMPLETED", "CANCELLED"]; if (typeof parsed !== "string" || !allowed.includes(parsed)) return res.status(400).json({ success: false, message: "Invalid raffle status" }); const raffle = await prisma.raffle.findUnique({ where: { id: raffleId } }); if (!raffle) return res.status(404).json({ success: false, message: "Raffle not found" }); if (raffle.createdByUserId !== req.userId) return res.status(403).json({ success: false, message: "Only the raffle creator can update this raffle" }); const requested = parsed as "DRAFT" | "SCHEDULED" | "ACTIVE" | "CLOSED" | "DRAWING" | "COMPLETED" | "CANCELLED"; const now = new Date(); if (requested === "SCHEDULED" && raffle.startsAt <= now) return res.status(400).json({ success: false, message: "A raffle whose start time has arrived cannot be scheduled" }); if (requested === "ACTIVE" && now >= raffle.endsAt) return res.status(400).json({ success: false, message: "A raffle cannot be activated after its end time" }); if (requested === "CLOSED" && raffle.status === "DRAFT") return res.status(400).json({ success: false, message: "Publish the raffle before closing entries" }); if (requested === "COMPLETED" || requested === "DRAWING") return res.status(400).json({ success: false, message: "Raffle completion is controlled by the draw workflow" }); const updated = await prisma.raffle.update({ where: { id: raffleId }, data: { status: requested } }); return res.json({ success: true, raffle: updated }); } catch (error) { next(error); } });
router.post("/:id/draw", requireAuth, async (req, res, next) => { try { if (!req.userId) return res.status(401).json({ success: false, message: "Authentication required" }); const raffleId = getRaffleId(req, res); if (!raffleId) return; const raffle = await prisma.raffle.findUnique({ where: { id: raffleId }, select: { createdByUserId: true, status: true, endsAt: true } }); if (!raffle) return res.status(404).json({ success: false, message: "Raffle not found" }); if (raffle.createdByUserId !== req.userId) return res.status(403).json({ success: false, message: "Only the raffle creator can draw this raffle" }); if (raffle.status !== "CLOSED") return res.status(400).json({ success: false, message: "Raffle entries must be closed before drawing winners" }); if (new Date() < raffle.endsAt) return res.status(400).json({ success: false, message: "Raffle cannot be drawn before its end time" }); const result = await drawRaffle(raffleId, req.userId); const notificationResults = await Promise.allSettled(result.winners.map((winner) => notifyWinner(raffleId, winner.id))); const notifications = notificationResults.map((item, index) => ({ winnerId: result.winners[index]?.id, sent: item.status === "fulfilled", error: item.status === "rejected" ? (item.reason instanceof Error ? item.reason.message : "Notification failed") : null })); return res.json({ success: true, ...result, notifications }); } catch (error) { next(error); } });
router.post("/:id/winners/:winnerId/notify", requireAuth, async (req, res, next) => { try { if (!req.userId) return res.status(401).json({ success: false, message: "Authentication required" }); const raffleId = getRaffleId(req, res); if (!raffleId) return; const winnerId = Array.isArray(req.params.winnerId) ? req.params.winnerId[0] : req.params.winnerId; if (!winnerId) return res.status(400).json({ success: false, message: "Invalid winner ID" }); const winner = await prisma.raffleWinner.findUnique({ where: { id: winnerId } }); if (!winner || winner.raffleId !== raffleId) return res.status(404).json({ success: false, message: "Raffle winner not found" }); const raffle = await prisma.raffle.findUnique({ where: { id: raffleId }, select: { createdByUserId: true } }); if (!raffle) return res.status(404).json({ success: false, message: "Raffle not found" }); if (raffle.createdByUserId !== req.userId) return res.status(403).json({ success: false, message: "Only the raffle creator can notify winners" }); const updated = await notifyWinner(raffleId, winnerId); return res.json({ success: true, winner: updated }); } catch (error) { next(error); } });

export default router;
