import express from "express";
import { securityMiddleware } from "../middleware/security.js";
import { errorHandler, notFoundHandler } from "../middleware/error-handler.js";
import { healthRouter } from "../routes/health.js";
import usersRouter from "../routes/users.js";
import authRouter from "../routes/auth.js";
import adminAuthRouter from "../routes/admin-auth.js";
import profileRouter from "../routes/profile.js";
import socialAccountsRouter from "../routes/social-accounts.js";
import xAuthRouter from "../routes/x-auth.js";
import discordAuthRouter from "../routes/discord-auth.js";
import telegramAuthRouter from "../routes/telegram-auth.js";
import walletsRouter from "../routes/wallets.js";
import projectsRouter from "../routes/projects.js";
import rafflesRouter from "../routes/raffles.js";
import publicRafflesRouter from "../routes/public-raffles.js";
import raffleEntriesRouter from "../routes/raffle-entries.js";
import raffleTasksRouter from "../routes/raffle-tasks.js";
import raffleWinnersRouter from "../routes/raffle-winners.js";
import alphaRouter from "../routes/alpha.js";
import chatRouter from "../routes/chat.js";
import adminRouter from "../routes/admin.js";
import adminLoginMethodsRouter from "../routes/admin-login-methods.js";
import pendingUserCleanupRouter from "../routes/pending-user-cleanup.js";

export function createApp() {
  const app = express();
  app.use(securityMiddleware);
  app.use(express.json({ limit: "4mb" }));
  app.use("/api/health", healthRouter);
  app.use("/api/users", usersRouter);
  app.use("/api/auth", authRouter);
  app.use("/api/auth/admin", adminAuthRouter);
  app.use("/api/profile", profileRouter);
  app.use("/api/social-accounts", socialAccountsRouter);
  app.use("/api/auth/x", xAuthRouter);
  app.use("/api/auth/discord", discordAuthRouter);
  app.use("/api/auth/telegram", telegramAuthRouter);
  app.use("/api/wallets", walletsRouter);
  app.use("/api/projects", projectsRouter);
  app.use("/api/raffles/public", publicRafflesRouter);
  app.use("/api/raffles", rafflesRouter);
  app.use("/api/raffles", raffleEntriesRouter);
  app.use("/api/raffles", raffleTasksRouter);
  app.use("/api/raffles", raffleWinnersRouter);
  app.use("/api/alpha", alphaRouter);
  app.use("/api/chat", chatRouter);
  app.use("/api/admin", adminRouter);
  app.use("/api/admin/login-methods", adminLoginMethodsRouter);
  app.use("/api/admin/pending-users", pendingUserCleanupRouter);
  app.use(notFoundHandler);
  app.use(errorHandler);
  return app;
}
