"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AdminLayout from "@/components/AdminLayout";
import { API_BASE_URL } from "@/lib/api-config";

type Raffle={id:string;title:string;prizeName:string;status:string;startsAt:string;endsAt:string;createdAt:string;cancelledAt?:string|null;winnerCount:number;project?:{name:string;logoUrl?:string|null}|null;createdBy:{username?:string|null;email?:string|null};_count:{entries:number;winners:number;tasks:number}};
type Winner={id:string;selectionRank:number;status:string;walletAddressSnapshot:string;user:{displayName?:string|null;username?:string|null;email?:string|null}};
async function api<T>(path:string,options:RequestInit={}){const headers=new Headers(options.headers);headers.set("Content-Type","application/json");const token=typeof window!=="undefined"?localStorage.getItem("raven_admin_token"):null;if(token)headers.set("Authorization",`Bearer ${token}`);const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers,credentials:"include",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message??`Request failed (${r.status})`);return d as T;}
export default function AdminRafflesPage(){const[raffles,setRaffles]=useState<Raffle[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");const[winners,setWinners]=useState<{raffle:Raffle;items:Winner[]}|null>(null);
 const load=async()=>{setLoading(true);setError("");try{setRaffles((await api<{raffles:Raffle[]}>("/admin/raffles")).raffles??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load raffles")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const del=async(id:string)=>{if(!confirm("Delete this raffle? Completed raffles with winners are retained."))return;setBusy(id);setError("");try{await api(`/admin/raffles/${id}`,{method:"DELETE"});setMessage("Raffle deleted.");await load()}catch(e){setError(e instanceof Error?e.message:"Raffle deletion failed")}finally{setBusy(null)}};
 const loadWinners=async(r:Raffle)=>{setBusy(r.id);try{const d=await api<{winners:Winner[]}>(`/admin/raffles/${r.id}/winners`);setWinners({raffle:r,items:d.winners??[]})}catch(e){setError(e instanceof Error?e.message:"Unable to load winners")}finally{setBusy(null)}};
 return <AdminLayout><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">RAFFLE MANAGEMENT</span><h1 className="mt-2 text-5xl font-medium">Manage raffles.</h1><p className="mt-3 text-sm text-zinc-600">Admin can review, cancel, draw and delete platform raffles.</p></div><button onClick={()=>void load()} className="rounded-lg border border-white/10 px-4 py-2 text-[10px] font-bold">Refresh</button></div>{error&&<div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">{message}</div>}{loading?<div className="py-20 text-center text-sm text-zinc-600">Loading raffles…</div>:raffles.length===0?<div className="py-20 text-center text-sm text-zinc-600">No raffles found.</div>:<div className="mt-6 space-y-4">{raffles.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-5"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-xl bg-black">{r.project?.logoUrl?<img src={r.project.logoUrl} alt="" className="h-full w-full object-cover"/>:<span>R</span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{r.title}</h2><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[9px] text-violet-300">{r.status}</span>{r.project&&<span className="text-[9px] text-zinc-600">{r.project.name}</span>}</div><p className="mt-2 text-sm text-zinc-500">Prize: {r.prizeName} · {r._count.entries} entries · {r._count.tasks} tasks · {r._count.winners} winners</p><p className="mt-1 text-[10px] text-zinc-700">Ends {new Date(r.endsAt).toLocaleString()} · Created by {r.createdBy.username||r.createdBy.email||"user"}</p></div></div><div className="mt-4 flex flex-wrap gap-2 border-t border-white/5 pt-4"><Link href={`/raffles/${r.id}`} target="_blank" className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-bold">View public</Link>{r._count.winners>0&&<button onClick={()=>void loadWinners(r)} disabled={busy===r.id} className="rounded-lg border border-blue-500/20 px-3 py-2 text-[10px] font-bold text-blue-300">Winners</button>}{!r.cancelledAt&&!['COMPLETED','DRAWING'].includes(r.status)&&<button onClick={()=>void del(r.id)} disabled={busy===r.id} className="ml-auto rounded-lg border border-red-500/20 px-3 py-2 text-[10px] font-bold text-red-300">Delete raffle</button>}</div></article>)}</div>}
 {winners&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><div className="max-h-[80vh] w-full max-w-2xl overflow-auto rounded-2xl border border-white/10 bg-[#0d0c11] p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Winners</h2><p className="text-sm text-zinc-500">{winners.raffle.title}</p></div><button onClick={()=>setWinners(null)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Close</button></div><div className="mt-5 space-y-2">{winners.items.length===0?<p className="text-sm text-zinc-600">No winners.</p>:winners.items.map(w=><div key={w.id} className="rounded-xl border border-white/10 p-4"><b>#{w.selectionRank} {w.user.displayName||w.user.username||w.user.email||"Unknown"}</b><div className="mt-1 text-xs text-zinc-500">{w.status} · {w.walletAddressSnapshot}</div></div>)}</div></div></div>}
 </div></AdminLayout>}
