export default function HowItWorks() {
  const steps = [
    ["01", "Connect once", "Sign in to Raven Oracle, then connect your X and Discord accounts. We use those connections to verify raffle requirements on your behalf."],
    ["02", "Choose a raffle", "Browse approved projects and active or scheduled raffles. Every raffle shows its prize, timing and required tasks before you enter."],
    ["03", "Complete the tasks", "Follow, like, repost or join the required community. Optional tasks never block your eligibility."],
    ["04", "Verify", "Raven Oracle checks the connected accounts against the task requirements. The server, not the browser, decides whether a task passed."],
    ["05", "Enter fairly", "Provide the EVM or Solana address that should receive a prize. No wallet connection is required just to participate."],
    ["06", "Draw & claim", "When a raffle closes, eligible entries are used for the auditable draw. Winners are notified and can claim through the winner flow."],
  ];
  return <main className="min-h-screen bg-[#07070a] text-zinc-100"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#07070a]/90 px-5 py-5 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="font-black tracking-[.18em]">RAVEN ORACLE</a><nav className="flex gap-5 text-xs text-zinc-500"><a href="/raffles">Raffles</a><a href="/projects">Projects</a><a href="/dashboard">Creator Studio</a></nav></div></header><section className="mx-auto max-w-5xl px-5 py-16"><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">HOW IT WORKS</span><h1 className="mt-3 text-5xl font-medium tracking-tight">From task to fair draw.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-500">Raven Oracle is built around one simple idea: raffle requirements should be easy for communities to publish and difficult to fake.</p><div className="mt-12 grid gap-4 md:grid-cols-2">{steps.map(([number,title,description]) => <article key={number} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-7"><span className="text-xs font-black text-violet-300">{number}</span><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{description}</p></article>)}</div><div className="mt-10 rounded-2xl border border-violet-400/15 bg-violet-500/[.04] p-7"><h2 className="font-bold">What Raven Oracle does not require</h2><div className="mt-4 grid gap-3 text-sm text-zinc-500 sm:grid-cols-3"><span>✓ No wallet connection</span><span>✓ No Raven Oracle Discord join</span><span>✓ No manual proof screenshots</span></div></div></section></main>;
}
