"use client";

import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type Raffle = { id: string; title: string; prizeName: string; prizeQuantity: number; startsAt: string; endsAt: string; status: string; winnerCount: number };
type Project = { id: string; name: string; description: string | null; websiteUrl: string | null; xUrl: string | null; discordUrl: string | null; logoUrl: string; category: string; status: string; raffles: Raffle[] };

export default function ProjectDetail({ params }: { params: Promise<{ id: string }> }) {
  const [project, setProject] = useState<Project | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { params.then(({ id }) => fetch(`${API}/projects/${id}`).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.message ?? "Project not found"); return d; }).then(d => setProject(d.project)).catch(e => setError(e instanceof Error ? e.message : "Unable to load project")).finally(() => setLoading(false))); }, [params]);
  if (loading) return <main className="min-h-screen bg-[#07070a] p-10 text-zinc-500">Loading project…</main>;
  if (error || !project) return <main className="min-h-screen bg-[#07070a] p-10 text-red-300">{error || "Project not found"}</main>;
  const live = project.raffles.filter(r => ["ACTIVE","SCHEDULED"].includes(r.status));
  return <main className="min-h-screen bg-[#07070a] text-zinc-100"><header className="border-b border-white/10 px-5 py-5"><div className="mx-auto flex max-w-6xl justify-between"><a href="/" className="font-black tracking-[.18em]">RAVEN ORACLE</a><a href="/projects" className="text-xs text-zinc-500">← Projects</a></div></header><section className="mx-auto max-w-6xl px-5 py-14"><div className="flex flex-col gap-6 md:flex-row md:items-center"><img src={project.logoUrl} alt="" className="h-24 w-24 rounded-2xl border border-white/10 object-cover"/><div><div className="text-[9px] font-black tracking-[.2em] text-violet-300/60">{project.category}</div><h1 className="mt-2 text-5xl font-medium tracking-tight">{project.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">{project.description || "No description yet."}</p></div></div><div className="mt-6 flex gap-3 text-xs">{project.websiteUrl && <a className="rounded-lg border border-white/10 px-3 py-2 text-zinc-400" href={project.websiteUrl} target="_blank">Website ↗</a>}{project.xUrl && <a className="rounded-lg border border-white/10 px-3 py-2 text-zinc-400" href={project.xUrl} target="_blank">X ↗</a>}{project.discordUrl && <a className="rounded-lg border border-white/10 px-3 py-2 text-zinc-400" href={project.discordUrl} target="_blank">Discord ↗</a>}</div><div className="mt-14 flex items-end justify-between"><div><span className="text-[9px] font-black tracking-[.2em] text-violet-300/60">RAFFLES</span><h2 className="mt-2 text-2xl font-medium">Live & upcoming</h2></div><a href="/raffles" className="text-xs text-zinc-500">Browse all →</a></div>{live.length === 0 ? <div className="mt-6 rounded-2xl border border-white/10 bg-[#0d0c11] p-10 text-center text-sm text-zinc-600">No live or upcoming raffles for this project.</div> : <div className="mt-6 grid gap-4 md:grid-cols-2">{live.map(r => <a key={r.id} href={`/raffles/${r.id}`} className="rounded-2xl border border-white/10 bg-[#0d0c11] p-5 hover:border-violet-400/30"><div className="flex justify-between"><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-zinc-500">{r.status}</span><span className="text-[10px] text-zinc-600">{r.winnerCount} winner{r.winnerCount === 1 ? "" : "s"}</span></div><h3 className="mt-5 text-xl font-medium">{r.title}</h3><p className="mt-2 text-xs text-zinc-500">Prize: {r.prizeName} · Qty {r.prizeQuantity}</p><p className="mt-5 text-[10px] text-zinc-600">Ends {new Date(r.endsAt).toLocaleString()}</p></a>)}</div>}</section></main>;
}
